# Generated by Django 6.0.7 on 2026-07-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
