# Generated by Django 6.0.7 on 2026-07-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='service',
            name='estimated_duration',
            field=models.PositiveIntegerField(default=30, help_text='Estimated duration in minutes'),
        ),
    ]
