# Generated by Django 6.0.7 on 2026-07-25 06:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('registration_number', models.CharField(help_text='Vehicle registration number', max_length=20, unique=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('variant', models.CharField(blank=True, max_length=50)),
                ('manufacture_year', models.PositiveSmallIntegerField(blank=True, help_text='year of manufacture(YYYY)', null=True)),
                ('color', models.CharField(blank=True, help_text='Vehicle color', max_length=30)),
                ('category', models.CharField(choices=[('HATCHBACK', 'Hatchback'), ('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('MUV', 'MUV'), ('PICKUP', 'Pickup'), ('VAN', 'Van'), ('TRUCK', 'Truck'), ('BUS', 'Bus')], max_length=20)),
                ('fuel_type', models.CharField(blank=True, choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('CNG', 'CNG'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid')], max_length=20)),
                ('transmission', models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], max_length=20)),
                ('current_kilometers', models.PositiveIntegerField(blank=True, help_text='Current odometer reading', null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['registration_number'],
            },
        ),
    ]
