# Generated by Django 6.0.7 on 2026-07-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['registration_number'], 'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='year',
            new_name='manufacture_year',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_kilometers',
            field=models.PositiveIntegerField(blank=True, help_text='Current odometer reading', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='variant',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('HATCHBACK', 'Hatchback'), ('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('MUV', 'MUV'), ('PICKUP', 'Pickup'), ('VAN', 'Van'), ('TRUCK', 'Truck'), ('BUS', 'Bus')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('CNG', 'CNG'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid')], max_length=20),
        ),
    ]
