# Generated by Django 6.0.7 on 2026-07-27 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='current_kilometers',
            new_name='odometer_reading',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='manufacture_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='year of manufacture(YYYY)', null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2027)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(db_index=True, help_text='Vehicle registration number', max_length=20, unique=True),
        ),
    ]
