# Generated by Django 6.0.7 on 2026-07-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, help_text='Vehicle color', max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='manufacture_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='year of manufactur(YYYY)', null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(help_text='Vehicle registration number', max_length=20, unique=True),
        ),
    ]
